version: "3.9"
services:
  python-ubuntu:
    image: python-ubuntu:latest # ビルド対象のコンテナイメージ名
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - http_proxy=$http_proxy
        - HTTPS_PROXY=$HTTPS_PROXY
        - https_proxy=$https_proxy
    volumes: # ボリュームのアタッチ
      - ./data:/root
    tty: true